-- Initial schema migration
-- Creates the pagamento table with embedded Transacao, Descricao and MetodoPagamento fields
-- Uses Postgres dialect

CREATE TABLE IF NOT EXISTS pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Transacao fields
    cartao VARCHAR(255) NOT NULL,
    transacao_id VARCHAR(255) NOT NULL,

    -- Descricao fields (flattened)
    valor NUMERIC(15,2) NOT NULL,
    data_hora TIMESTAMP NOT NULL,
    estabelecimento VARCHAR(255) NOT NULL,
    nsu VARCHAR(10) NOT NULL,
    codigo_autorizacao VARCHAR(9) NOT NULL,
    transacao_status_type VARCHAR(50),

    -- MetodoPagamento fields (flattened)
    metodo_pagamento VARCHAR(50) NOT NULL,
    parcelas INTEGER NOT NULL,

    CONSTRAINT uq_pagamento_transacao_id UNIQUE (transacao_id),
    CONSTRAINT uq_pagamento_nsu UNIQUE (nsu),
    CONSTRAINT uq_pagamento_codigo_autorizacao UNIQUE (codigo_autorizacao)
);

-- Optional indexes to speed lookups used in the code
CREATE INDEX IF NOT EXISTS idx_pagamento_transacao_id ON pagamento(transacao_id);
CREATE INDEX IF NOT EXISTS idx_pagamento_nsu ON pagamento(nsu);
CREATE INDEX IF NOT EXISTS idx_pagamento_codigo_autorizacao ON pagamento(codigo_autorizacao);

